# Generated by Django 3.2.20 on 2023-09-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='district',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dealer',
            name='fullname',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dealer',
            name='housename',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dealer',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='dealer',
            name='pincode',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True),
        ),
    ]
