# Generated by Django 3.2.20 on 2023-09-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0002_auto_20230928_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
