# Generated by Django 3.2.20 on 2023-09-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0003_alter_dealer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='district',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='housename',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='pincode',
        ),
    ]
