# Generated by Django 3.2.20 on 2023-11-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapmapp', '0004_auto_20231120_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
